// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eraft.proto

package eraftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EntryType 条目类型
type EntryType int32

const (
	EntryType_EntryNormal     EntryType = 0
	EntryType_EntryConfChange EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "EntryNormal",
	1: "EntryConfChange",
}

var EntryType_value = map[string]int32{
	"EntryNormal":     0,
	"EntryConfChange": 1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}

func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{0}
}

type ConfChangeType int32

const (
	ConfChangeType_AddNode    ConfChangeType = 0
	ConfChangeType_RemoveNode ConfChangeType = 1
)

var ConfChangeType_name = map[int32]string{
	0: "AddNode",
	1: "RemoveNode",
}

var ConfChangeType_value = map[string]int32{
	"AddNode":    0,
	"RemoveNode": 1,
}

func (x ConfChangeType) String() string {
	return proto.EnumName(ConfChangeType_name, int32(x))
}

func (ConfChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{1}
}

// MessageType 同样需要Setp方法处理的本地信息
type MessageType int32

const (
	// 选举超时 指示本节点进入选举
	MessageType_MsgHup MessageType = 0
	// 成为 Leader 指示本节点向followers发送 MsgHeartbeat
	MessageType_MsgBeat MessageType = 1
	// 提议向 Leader 的日志条目中添加信息
	MessageType_MsgPropose MessageType = 2
	// 包含要复制的日志条目
	MessageType_MsgAppend MessageType = 3
	// 回应append
	MessageType_MsgAppendResponse MessageType = 4
	// 请求选举投票
	MessageType_MsgRequestVote MessageType = 5
	// 回应选举投票
	MessageType_MsgRequestVoteResponse MessageType = 6
	// TODO 请求安装快照消息
	MessageType_MsgSnapshot MessageType = 7
	// Leader 向 followers 发送的心跳
	MessageType_MsgHeartbeat MessageType = 8
	// 心跳回应
	MessageType_MsgHeartbeatResponse MessageType = 9
	// TODO 要求 目标Leader 下台
	MessageType_MsgTransferLeader MessageType = 11
	// Leader 向别的目标Leader发送此消息要求对方立即下台
	MessageType_MsgTimeoutNow MessageType = 12
)

var MessageType_name = map[int32]string{
	0:  "MsgHup",
	1:  "MsgBeat",
	2:  "MsgPropose",
	3:  "MsgAppend",
	4:  "MsgAppendResponse",
	5:  "MsgRequestVote",
	6:  "MsgRequestVoteResponse",
	7:  "MsgSnapshot",
	8:  "MsgHeartbeat",
	9:  "MsgHeartbeatResponse",
	11: "MsgTransferLeader",
	12: "MsgTimeoutNow",
}

var MessageType_value = map[string]int32{
	"MsgHup":                 0,
	"MsgBeat":                1,
	"MsgPropose":             2,
	"MsgAppend":              3,
	"MsgAppendResponse":      4,
	"MsgRequestVote":         5,
	"MsgRequestVoteResponse": 6,
	"MsgSnapshot":            7,
	"MsgHeartbeat":           8,
	"MsgHeartbeatResponse":   9,
	"MsgTransferLeader":      11,
	"MsgTimeoutNow":          12,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{2}
}

// Entry 条目
// 1. entry_type 类型
// 2. term 选举轮次
// 3. index 提案idx(id)
// 4. data 数据
type Entry struct {
	EntryType            EntryType `protobuf:"varint,1,opt,name=entry_type,json=entryType,proto3,enum=eraftpb.EntryType" json:"entry_type,omitempty"`
	Term                 uint64    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetEntryType() EntryType {
	if m != nil {
		return m.EntryType
	}
	return EntryType_EntryNormal
}

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// HardState 节点状态 当前 term, commit index, vote record
type HardState struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Vote                 uint64   `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Commit               uint64   `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HardState) Reset()         { *m = HardState{} }
func (m *HardState) String() string { return proto.CompactTextString(m) }
func (*HardState) ProtoMessage()    {}
func (*HardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{1}
}

func (m *HardState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardState.Unmarshal(m, b)
}
func (m *HardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardState.Marshal(b, m, deterministic)
}
func (m *HardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardState.Merge(m, src)
}
func (m *HardState) XXX_Size() int {
	return xxx_messageInfo_HardState.Size(m)
}
func (m *HardState) XXX_DiscardUnknown() {
	xxx_messageInfo_HardState.DiscardUnknown(m)
}

var xxx_messageInfo_HardState proto.InternalMessageInfo

func (m *HardState) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *HardState) GetVote() uint64 {
	if m != nil {
		return m.Vote
	}
	return 0
}

func (m *HardState) GetCommit() uint64 {
	if m != nil {
		return m.Commit
	}
	return 0
}

// ConfState
// 1. nodes 包含当前raft的所有节点
type ConfState struct {
	// all node id
	Nodes                []uint64 `protobuf:"varint,1,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfState) Reset()         { *m = ConfState{} }
func (m *ConfState) String() string { return proto.CompactTextString(m) }
func (*ConfState) ProtoMessage()    {}
func (*ConfState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{2}
}

func (m *ConfState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfState.Unmarshal(m, b)
}
func (m *ConfState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfState.Marshal(b, m, deterministic)
}
func (m *ConfState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfState.Merge(m, src)
}
func (m *ConfState) XXX_Size() int {
	return xxx_messageInfo_ConfState.Size(m)
}
func (m *ConfState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfState.DiscardUnknown(m)
}

var xxx_messageInfo_ConfState proto.InternalMessageInfo

func (m *ConfState) GetNodes() []uint64 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// ConfChange is the data that attach on entry with EntryConfChange type
// TODO
type ConfChange struct {
	ChangeType ConfChangeType `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=eraftpb.ConfChangeType" json:"change_type,omitempty"`
	// node will be add/remove
	NodeId               uint64   `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Context              []byte   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfChange) Reset()         { *m = ConfChange{} }
func (m *ConfChange) String() string { return proto.CompactTextString(m) }
func (*ConfChange) ProtoMessage()    {}
func (*ConfChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{3}
}

func (m *ConfChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfChange.Unmarshal(m, b)
}
func (m *ConfChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfChange.Marshal(b, m, deterministic)
}
func (m *ConfChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfChange.Merge(m, src)
}
func (m *ConfChange) XXX_Size() int {
	return xxx_messageInfo_ConfChange.Size(m)
}
func (m *ConfChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfChange.DiscardUnknown(m)
}

var xxx_messageInfo_ConfChange proto.InternalMessageInfo

func (m *ConfChange) GetChangeType() ConfChangeType {
	if m != nil {
		return m.ChangeType
	}
	return ConfChangeType_AddNode
}

func (m *ConfChange) GetNodeId() uint64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ConfChange) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

// SnapshotMetadata
// 1. conf_state
// 2. index 日志index
// 3. term 最后一个应用于快照的log
type SnapshotMetadata struct {
	ConfState            *ConfState `protobuf:"bytes,1,opt,name=conf_state,json=confState,proto3" json:"conf_state,omitempty"`
	Index                uint64     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term                 uint64     `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SnapshotMetadata) Reset()         { *m = SnapshotMetadata{} }
func (m *SnapshotMetadata) String() string { return proto.CompactTextString(m) }
func (*SnapshotMetadata) ProtoMessage()    {}
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{4}
}

func (m *SnapshotMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotMetadata.Unmarshal(m, b)
}
func (m *SnapshotMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotMetadata.Marshal(b, m, deterministic)
}
func (m *SnapshotMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotMetadata.Merge(m, src)
}
func (m *SnapshotMetadata) XXX_Size() int {
	return xxx_messageInfo_SnapshotMetadata.Size(m)
}
func (m *SnapshotMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotMetadata proto.InternalMessageInfo

func (m *SnapshotMetadata) GetConfState() *ConfState {
	if m != nil {
		return m.ConfState
	}
	return nil
}

func (m *SnapshotMetadata) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SnapshotMetadata) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type Snapshot struct {
	Data                 []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             *SnapshotMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{5}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Snapshot) GetMetadata() *SnapshotMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Message struct {
	MsgType              MessageType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=eraftpb.MessageType" json:"msg_type,omitempty"`
	To                   uint64      `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From                 uint64      `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Term                 uint64      `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogTerm              uint64      `protobuf:"varint,5,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Index                uint64      `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Entries              []*Entry    `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	Commit               uint64      `protobuf:"varint,8,opt,name=commit,proto3" json:"commit,omitempty"`
	Snapshot             *Snapshot   `protobuf:"bytes,9,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Reject               bool        `protobuf:"varint,10,opt,name=reject,proto3" json:"reject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a50581ee96b01, []int{6}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_MsgHup
}

func (m *Message) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Message) GetLogTerm() uint64 {
	if m != nil {
		return m.LogTerm
	}
	return 0
}

func (m *Message) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Message) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Message) GetCommit() uint64 {
	if m != nil {
		return m.Commit
	}
	return 0
}

func (m *Message) GetSnapshot() *Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *Message) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

func init() {
	proto.RegisterEnum("eraftpb.EntryType", EntryType_name, EntryType_value)
	proto.RegisterEnum("eraftpb.ConfChangeType", ConfChangeType_name, ConfChangeType_value)
	proto.RegisterEnum("eraftpb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Entry)(nil), "eraftpb.Entry")
	proto.RegisterType((*HardState)(nil), "eraftpb.HardState")
	proto.RegisterType((*ConfState)(nil), "eraftpb.ConfState")
	proto.RegisterType((*ConfChange)(nil), "eraftpb.ConfChange")
	proto.RegisterType((*SnapshotMetadata)(nil), "eraftpb.SnapshotMetadata")
	proto.RegisterType((*Snapshot)(nil), "eraftpb.Snapshot")
	proto.RegisterType((*Message)(nil), "eraftpb.Message")
}

func init() {
	proto.RegisterFile("eraft.proto", fileDescriptor_8b1a50581ee96b01)
}

var fileDescriptor_8b1a50581ee96b01 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0xc5, 0xf9, 0xb3, 0x3d, 0x0e, 0x61, 0x99, 0x2f, 0x1f, 0x98, 0x5e, 0xa5, 0xbe, 0x8a, 0x90,
	0xa0, 0x82, 0xaa, 0x52, 0x6f, 0x29, 0xaa, 0x44, 0xd5, 0x1a, 0x55, 0x86, 0xf6, 0x36, 0x5a, 0xec,
	0x89, 0x49, 0x85, 0xbd, 0xae, 0x77, 0xa1, 0xe4, 0x9d, 0xfa, 0x76, 0x7d, 0x81, 0x6a, 0x37, 0xce,
	0xc6, 0xa1, 0x77, 0x73, 0x26, 0x67, 0xcf, 0x9c, 0x39, 0x9a, 0x18, 0x02, 0xaa, 0xf9, 0x5c, 0x9d,
	0x56, 0xb5, 0x50, 0x02, 0x5d, 0x03, 0xaa, 0xbb, 0xe8, 0x19, 0xfa, 0x1f, 0x4b, 0x55, 0x2f, 0xf1,
	0x0c, 0x80, 0x74, 0x31, 0x53, 0xcb, 0x8a, 0x42, 0x67, 0xe2, 0x4c, 0x47, 0xe7, 0x78, 0xda, 0xd0,
	0x4e, 0x0d, 0xe7, 0x76, 0x59, 0x51, 0xe2, 0xd3, 0xba, 0x44, 0x84, 0x9e, 0xa2, 0xba, 0x08, 0x3b,
	0x13, 0x67, 0xda, 0x4b, 0x4c, 0x8d, 0x63, 0xe8, 0x2f, 0xca, 0x8c, 0x9e, 0xc3, 0xae, 0x69, 0xae,
	0x80, 0x66, 0x66, 0x5c, 0xf1, 0xb0, 0x37, 0x71, 0xa6, 0xc3, 0xc4, 0xd4, 0xd1, 0x67, 0xf0, 0xaf,
	0x78, 0x9d, 0xdd, 0x28, 0xae, 0x36, 0x52, 0x4e, 0x4b, 0x0a, 0xa1, 0xf7, 0x24, 0x14, 0xad, 0xe5,
	0x75, 0x8d, 0x07, 0x30, 0x48, 0x45, 0x51, 0x2c, 0x54, 0xa3, 0xdf, 0xa0, 0xe8, 0x35, 0xf8, 0x97,
	0xa2, 0x9c, 0xaf, 0xc4, 0xc6, 0xd0, 0x2f, 0x45, 0x46, 0x32, 0x74, 0x26, 0x5d, 0xed, 0xc1, 0x80,
	0x68, 0x09, 0xa0, 0x29, 0x97, 0xf7, 0xbc, 0xcc, 0x09, 0xdf, 0x43, 0x90, 0x9a, 0xaa, 0xbd, 0xef,
	0xa1, 0xdd, 0x77, 0xc3, 0x34, 0x4b, 0x43, 0x6a, 0x6b, 0x3c, 0x04, 0x57, 0x0b, 0xce, 0x16, 0x59,
	0xe3, 0x6c, 0xa0, 0xe1, 0xa7, 0x0c, 0x43, 0x70, 0x53, 0x51, 0x2a, 0x7a, 0x5e, 0x99, 0x1b, 0x26,
	0x6b, 0x18, 0x09, 0x60, 0x37, 0x25, 0xaf, 0xe4, 0xbd, 0x50, 0x31, 0x29, 0xae, 0xd7, 0xd7, 0x79,
	0xa7, 0xa2, 0x9c, 0xcf, 0xa4, 0xb6, 0x6c, 0xe6, 0x07, 0xad, 0xbc, 0xed, 0x32, 0x89, 0x9f, 0xb6,
	0xf7, 0x5a, 0x65, 0xdb, 0x79, 0x91, 0xad, 0x89, 0xae, 0xbb, 0x89, 0x2e, 0xfa, 0x06, 0xde, 0x7a,
	0xa0, 0xcd, 0xde, 0xd9, 0x64, 0x8f, 0xef, 0xc0, 0x2b, 0x1a, 0x23, 0x46, 0x2c, 0x38, 0x3f, 0xb2,
	0xa3, 0x5f, 0x3a, 0x4d, 0x2c, 0x35, 0xfa, 0xdd, 0x01, 0x37, 0x26, 0x29, 0x79, 0x4e, 0xf8, 0x06,
	0xbc, 0x42, 0xe6, 0xed, 0xf4, 0xc6, 0x56, 0xa2, 0xe1, 0x98, 0xe8, 0xdc, 0x42, 0xe6, 0x26, 0xb7,
	0x11, 0x74, 0x94, 0x68, 0xac, 0x77, 0x94, 0xd0, 0xbe, 0xe6, 0xb5, 0xb0, 0xbe, 0x75, 0x6d, 0x77,
	0xe9, 0xb5, 0xce, 0xe0, 0x08, 0xbc, 0x07, 0x91, 0xcf, 0x4c, 0xbf, 0x6f, 0xfa, 0xee, 0x83, 0xc8,
	0x6f, 0xb7, 0x8e, 0x6d, 0xd0, 0x0e, 0x64, 0x0a, 0xae, 0xbe, 0xd1, 0x05, 0xc9, 0xd0, 0x9d, 0x74,
	0xa7, 0xc1, 0xf9, 0x68, 0xfb, 0x8c, 0x93, 0xf5, 0xcf, 0xad, 0x6b, 0xf2, 0xda, 0xd7, 0x84, 0x27,
	0xe0, 0xc9, 0x26, 0x85, 0xd0, 0x37, 0xf1, 0xec, 0xff, 0x13, 0x4f, 0x62, 0x29, 0x5a, 0xa6, 0xa6,
	0x1f, 0x94, 0xaa, 0x10, 0x26, 0xce, 0xd4, 0x4b, 0x1a, 0x74, 0x7c, 0x06, 0xbe, 0xfd, 0xdf, 0xe0,
	0x1e, 0x04, 0x06, 0x5c, 0x8b, 0xba, 0xe0, 0x0f, 0x6c, 0x07, 0xff, 0x83, 0x3d, 0xd3, 0xd8, 0x9c,
	0x1a, 0x73, 0x8e, 0x4f, 0x60, 0xb4, 0x7d, 0x7a, 0x18, 0x80, 0x7b, 0x91, 0x65, 0xd7, 0x22, 0x23,
	0xb6, 0x83, 0x23, 0x80, 0x84, 0x0a, 0xf1, 0x44, 0x06, 0x3b, 0xc7, 0x7f, 0x1c, 0x08, 0x5a, 0x61,
	0x23, 0xc0, 0x20, 0x96, 0xf9, 0xd5, 0x63, 0xc5, 0x76, 0xf4, 0xc3, 0x58, 0xe6, 0x1f, 0x88, 0x2b,
	0xe6, 0xe8, 0x87, 0xb1, 0xcc, 0xbf, 0xd6, 0xa2, 0x12, 0x92, 0x58, 0x07, 0x77, 0xc1, 0x8f, 0x65,
	0x7e, 0x51, 0x55, 0x54, 0x66, 0xac, 0x8b, 0xff, 0xc3, 0xbe, 0x85, 0x09, 0xc9, 0x4a, 0x94, 0x92,
	0x58, 0x0f, 0x11, 0x46, 0xb1, 0xcc, 0x13, 0xfa, 0xf9, 0x48, 0x52, 0x7d, 0x17, 0x8a, 0x58, 0x1f,
	0x5f, 0xc1, 0xc1, 0x76, 0xcf, 0xf2, 0x07, 0x7a, 0xc7, 0x58, 0xe6, 0xeb, 0x84, 0x98, 0x8b, 0x0c,
	0x86, 0xda, 0x0f, 0xf1, 0x5a, 0xdd, 0x69, 0x23, 0x1e, 0x86, 0x30, 0x6e, 0x77, 0xec, 0x63, 0xbf,
	0xf1, 0x70, 0x5b, 0xf3, 0x52, 0xce, 0xa9, 0xfe, 0x42, 0x3c, 0xa3, 0x9a, 0x05, 0xb8, 0x0f, 0xbb,
	0xba, 0xbd, 0x28, 0x48, 0x3c, 0xaa, 0x6b, 0xf1, 0x8b, 0x0d, 0xef, 0x06, 0xe6, 0x1b, 0xf6, 0xf6,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x54, 0xf9, 0x94, 0xd2, 0x04, 0x00, 0x00,
}
